# The contents of the file: /omp_ir_mapper/omp_ir_mapper/config/default.toml

[clang]
flags = ["-fopenmp", "-fopenmp-targets=host", "-O2"]

[report]
generate_html = true
output_directory = "reports"
output_format = "json"